url: http://csinva.github.io
baseurl: ""

# Site Settings
title: Chandan Singh
description: "Chandan Singh Homepage"
keywords: "Chandan, Singh, Machine Learning, Berkeley, Interpretability"
collections:
 research_ovws:
    name: research_ovws
    output: true
 blog:
    name: blog
    output: true
 notes:
    name: Notes
    documentation: https://github.com/Shopify/liquid/wiki/Liquid-for-Designers
    output: true
 timeline_blurbs:
    name: timeline_blurbs
    output: true

markdown: kramdown
exclude: ["Rakefile", "LICENSE", "readme.md"]
